version: '3.7'

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./req_crawler:/app
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: req
      MYSQL_USER: req
      MYSQL_ROOT_PASSWORD: req
